version: '3.8'

services:
  besu:
    image: hyperledger/besu:latest
    container_name: ledger-besu
    volumes:
      - ./config:/config
      - ./data:/var/lib/besu
    ports:
      - "8545:8545"    # HTTP-RPC
      - "8546:8546"    # WS-RPC
      - "8547:8547"    # GraphQL
      - "9545:9545"    # Metrics
      - "30303:30303"  # P2P TCP
      - "30303:30303/udp" # P2P UDP
    command: >
      --genesis-file=/config/genesis.json
      --network-id=1337
      --metrics-enabled
      --metrics-host=0.0.0.0
      --metrics-port=9545
      --rpc-http-enabled
      --rpc-http-host=0.0.0.0
      --rpc-http-port=8545
      --rpc-ws-enabled
      --rpc-ws-host=0.0.0.0
      --rpc-ws-port=8546
      --graphql-http-enabled
      --graphql-http-host=0.0.0.0
      --graphql-http-port=8547
      --miner-enabled
      --miner-coinbase=0x2B70E2087473622A4DC2aD8E03F4253BFb6Cf79E
      --rpc-http-cors-origins="*"
      --host-allowlist="*"
    networks:
      - besu_net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - besu_net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - besu_net

networks:
  besu_net:
    driver: bridge