version: '3.8'

services:
  besu:
    container_name: ledger-besu
    image: hyperledger/besu:latest
    command: >
        --network=dev
        --metrics-enabled
        --metrics-host=0.0.0.0
        --metrics-port=9545
        --rpc-http-enabled
        --rpc-http-host=0.0.0.0
        --rpc-http-port=8545
        --rpc-ws-enabled
        --rpc-ws-host=0.0.0.0
        --rpc-ws-port=8546
        --graphql-http-enabled
        --graphql-http-host=0.0.0.0
        --graphql-http-port=8547
        --network-id=1338
    volumes:
      - besu-data:/opt/besu/data
      - besu-config:/etc/besu
      - ./config:/config
      - ./data:/var/lib/besu
    ports:
      - "8545:8545"
      - "9545:9545"
      - "30303:30303"
    networks:
      - besu_net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - besu_net

  # grafana:
  #   image: grafana/grafana
  #   container_name: grafana
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - prometheus
  #   networks:
  #     - besu_net

  mysql:
    image: mysql:8.0
    container_name: app-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${HOST_PORT}:${DB_PORT}
    volumes:
      - mysql_data:/var/lib/mysql
      - ../mysql-init:/docker-entrypoint-initdb.d
    networks:
      - besu_net
      

volumes:
  besu-data:
  besu-config:
  mysql_data:
  mysql_init:
  
# 👇 Add this section to define the network
networks:
  besu_net:
    driver: bridge