version: '3.8'

services:
  besu:
    container_name: ledger-besu
    image: hyperledger/besu:latest
    command: >
        --genesis-file=/config/genesis.json
        --data-path=/opt/besu/data
        --logging=DEBUG
        --rpc-http-enabled
        --rpc-http-host=0.0.0.0
        --rpc-http-port=8545
        --rpc-http-api=ETH,NET,WEB3,DEBUG,TXPOOL,ADMIN
        --rpc-http-cors-origins="*"
        --host-allowlist="*"
        --miner-enabled
        --miner-coinbase=0xc73aF3677eBc555Fc631d3EdfCE675A656b684e5
        --min-gas-price=0
    volumes:
      - besu-data:/opt/besu/data
      - besu-config:/etc/besu
      - ./config:/config
      - ./data:/var/lib/besu
    ports:
      - "8545:8545"
      - "9545:9545"
      - "30303:30303"
    networks:
      - besu_net

  # prometheus:
  #   image: prom/prometheus
  #   container_name: prometheus
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #   ports:
  #     - "9090:9090"
  #   networks:
  #     - besu_net

  mysql:
    image: mysql:8.0
    container_name: app-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${HOST_PORT}:${DB_PORT}
    volumes:
      - mysql_data:/var/lib/mysql
      - ../mysql-init:/docker-entrypoint-initdb.d
    networks:
      - besu_net
      

volumes:
  besu-data:
  besu-config:
  mysql_data:
  mysql_init:
  
# 👇 Add this section to define the network
networks:
  besu_net:
    driver: bridge