version: '0.1'

services:
  # client:
  #   image: fsc-client7:latest
  #   environment:
  #     - VITE_SERVER_PORT=${VITE_SERVER_PORT:-3010}
  #   ports:
  #     - "5173:5173"

  server:
    image: fsc-server:latest
    environment:
      - DB_HOST=${DB_HOST:-127.0.0.1}
      - DB_PORT=${DB_PORT:-3306}
      - DB_NAME=${DB_NAME:-food_supply_chain}
      - DB_USER=${DB_USER:-appuser}
      - DB_PASSWORD=${DB_PASSWORD:-apppassword}
      - SERVER_PORT=${SERVER_PORT:-3010}
      - VITE_SERVER_PORT=${VITE_SERVER_PORT:-3010}
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret}
      - RPC_URL=${RPC_URL:-http://besu:8545}
      - TOKEN_ADDRESS=${TOKEN_ADDRESS:-0x2E6A0e0106F37A045a8b0B9C9357Ffe9a873Fa4c}
      - DEPLOYER_PRIVATE_KEY=${DEPLOYER_PRIVATE_KEY:-7a18769fc1e450f623619bb54b67e118a2462ae5f8f4be8f066de5a77cfc3cf1}
    ports:
      - "3010:3010"
    networks:
      - besu_net

networks:
  besu_net:
    external: true
      
