version: '0.1'

services:
  # client:
  #   image: fsc-client7:latest
  #   environment:
  #     - VITE_SERVER_PORT=${VITE_SERVER_PORT:-3010}
  #   ports:
  #     - "5173:5173"

  server:
    image: fsc-server:latest
    environment:
      - DB_HOST=${DB_HOST:-127.0.0.1}
      - DB_PORT=${DB_PORT:-3306}
      - DB_NAME=${DB_NAME:-food_supply_chain}
      - DB_USER=${DB_USER:-appuser}
      - DB_PASSWORD=${DB_PASSWORD}
      - SERVER_PORT=${SERVER_PORT:-3010}
      - VITE_SERVER_PORT=${VITE_SERVER_PORT:-3010}
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret}
    ports:
      - "3010:3010"