version: '0.1'

services:
  # client:
  #   image: fsc-client7:latest
  #   environment:
  #     - VITE_SERVER_PORT=${VITE_SERVER_PORT:-3010}
  #   ports:
  #     - "5173:5173"

  server:
    image: fsc-server:latest
    environment:
      - DB_HOST=${DB_HOST:-mysql}
      - DB_PORT=${DB_PORT:-3306}
      - DB_NAME=${DB_NAME:-food_supply_chain}
      - DB_USER=${DB_USER:-appuser}
      - DB_PASSWORD=${DB_PASSWORD:-apppassword}
      - SERVER_PORT=${SERVER_PORT:-3010}
      - VITE_SERVER_PORT=${VITE_SERVER_PORT:-3010}
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret}
      - RPC_URL=${RPC_URL:-http://besu:8545}
      - TOKEN_ADDRESS=${TOKEN_ADDRESS}
      - DEPLOYER_PRIVATE_KEY=${DEPLOYER_PRIVATE_KEY}
    ports:
      - "3010:3010"
    networks:
      - besu_net

networks:
  besu_net:
    external: true
      
